### ISSUE TITLE
No battery info

### ISSUE THREAD

**Issue by Droidriven** [IridiumIon/DroidManager#1] opened 2016-08-17 02:02 UTC
I tried this out, so far it seems ok out of what works.

Here is what worked so far for me on my S3 running an OctOS 6.0 weekly (for testing but gets changed with every weekly) with the latest SuperSU and TWRP(I keep them up to date).

1) Device info and the build.prop display works fine
2) Application Manager displays all apps and all features appear to work
3) Backup/Restore works apparently

Nothing else is displaying or doing anything.

**Comment by 0xFireball** [comment] 2016-08-17 04:29
Yes, this for the most part seems to be expected behavior, I have a feature list in the Readme; sorry for not being more clear about it: the features that have not been implemented with will do nothing. I will update the README.

I am still working on the other features.

However, your title says: no battery info...do you mean that the battery tab isn't working? Can you post a screenshot?

**Comment by Droidriven** [comment] 2016-08-17 05:46
The tab is fine and it displays the list of values but shows no actual values.

**Comment by 0xFireball** [comment] 2016-08-17 06:35
Can you send a screenshot please?

**Comment by Droidriven** [comment] 2016-08-23 02:01
Yes, I can, don't see the point though. I'll get a shit tonight and upload
it.

**Comment by 0xFireball** [comment] 2016-08-31 01:49
I'll close this issue, as it is now included in #2 .

**Closed by 0xFireball** 2016-08-31 01:49 UTC

**Comment by Droidriven** [comment] 2016-12-13 23:30
What is the progress so far? Is there anything you want/need me to do? is development still going on DroidManager?

**Comment by 0xFireball** [comment] 2016-12-13 23:49
So, I'm planning to rebuild it with Avalonia, which will give me cross platform UI. Development had been paused for a bit while I worked on other things. I'll soon begin the new work in another branch. Once I start that, if you're willing to help, I'd be really grateful to have someone occasionally test out releases and provide feedback.

Thanks for your interest! It's much appreciated!
